version: '3'

services:
  convictionsai-services-api:
    platform: "linux/amd64"
    hostname: dev.local
    container_name: convictionsai-services-api
    build:
      context: .
    env_file: .env.docker
    ports:
      - "8080"
    networks:
      convictionsai:

networks:
  convictionsai:
    external: true
